version: '3.9'
services:
  # PHP-FPM Service
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    # Mounts the local 'app' directory to the container's Nginx root
      - ./app:/var/www/html  
    depends_on:
    # Depends on the MySQL database service
      - mysql-db  

  # NGINX Service
  webserver:
    image: nginx:latest
    #build:
      #context: .
      #dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./nginx/sites-available:/etc/nginx/conf.d/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro	
      - ./certbot/www/:/var/www/certbot/:ro

  # MySQL Database Service
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hccomputer@1124
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pw@1124
    ports:
    # Maps port 3306 on the host to port 3306 on the MySQL container
      - "3306:3306"  

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    # Links the PHPMyAdmin service to the MySQL database service
      - mysql-db 
    ports:
      - "81:80" 
    environment:
      PMA_HOST: mysql-db
      # Use MySQL root password for PHPMyAdmin
      MYSQL_ROOT_PASSWORD: hccomputer@1124 

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
