# Use the official NGINX image
FROM nginx:latest
# Remove default NGINX configuration
RUN rm /etc/nginx/conf.d/*.conf
# Copy your custom NGINX configuration
# COPY ./nginx/sites-available/*.conf /etc/nginx/conf.d/sites-available
